### ISSUE TITLE
Return key in System > Preferences executes export

### ISSUE THREAD

**Issue by nickdunn** [symphonycms/export_ensemble#12]
Because this extension adds two `button` elements without `type` attributes, the browser treats them as submit buttons. This means that hitting the return key (think you will submit the preferences page form) will actually trigger the first Export Ensemble button instead. Giving the buttons an explicit `type` attribute (of `button`) will prevent this. But will require JavaScript event handlers to replace the existing functionality (to submit the form with the appropriate `action[...]`).

**Comment by nitriques** [comment]
Can't reproduce!
