### ISSUE TITLE
Fatal error when installing from ensemble

### ISSUE THREAD

**Issue by vlad-ghita** [symphonycms/export_ensemble#14]
I just tried to install from ensemble and I get [this error](http://www.freeimagehosting.net/93cti).

It goes like this: Export ensemble tries to enable Page LHandles:

    Extension_page_lhandles->enable( )

This extension tries to get a list of existing datasources:

    DatasourceManager::listAll( )

In this method from `DatasourceManager`, on line 123 it dies trying to get an instance of `ExtensionManager`:

    $extensions = Symphony::ExtensionManager()->listInstalledHandles();

Any thoughts?

**Comment by nitriques** [comment]
Can't find any calls to Symphony::ExtensionManager()->listInstalledHandles();
